confirmacion de  contenedor docker2

diff --git a/.github/workflows/pipeline-build.yaml b/.github/workflows/pipeline-build.yaml
--- a/.github/workflows/pipeline-build.yaml
+++ b/.github/workflows/pipeline-build.yaml
@@ -56,9 +56,18 @@ jobs:
         run: |
           docker run -d -p 8080:80 webgoat/test
 
-      - name: "comoartir imagen"
+      - name: "Esperar a que el contenedor se inicie"
+        run: sleep 10
+
+      - name: "Verificar estado del contenedor"
+        run: docker ps | grep webgoat/test
+
+      - name: "Manejo de errores si el contenedor no se encuentra"
         run: |
-        docker push webgoat/test:latest
+          if ! docker ps | grep -q webgoat/test; then
+            echo "Error: El contenedor no se ha creado correctamente."
+            exit 1
+          fi
 
       - name: "Confirmación de finalización"
         run: echo "El flujo de trabajo se ha completado con éxito."
