cambios pipeline3

diff --git a/.github/workflows/pipeline-build.yaml b/.github/workflows/pipeline-build.yaml
--- a/.github/workflows/pipeline-build.yaml
+++ b/.github/workflows/pipeline-build.yaml
@@ -54,6 +54,16 @@ jobs:
           echo "Image Reference: $IMAGE_NAME"
           docker run -d -p 8080:80 $IMAGE_NAME
 
+      - name: "Verificar estado del contenedor"
+        run: docker ps | grep $IMAGE_NAME
+
+      - name: "Manejo de errores si el contenedor no se encuentra"
+        run: |
+          if ! docker ps | grep -q $IMAGE_NAME; then
+            echo "Error: El contenedor no se ha creado correctamente."
+            exit 1
+          fi
+
       - name: "Ejecutar escáner de vulnerabilidades Trivy"
         uses: aquasecurity/trivy-action@master
         with:
@@ -68,15 +78,6 @@ jobs:
       - name: "Esperar a que el contenedor se inicie"
         run: sleep 10
 
-      - name: "Verificar estado del contenedor"
-        run: docker ps | grep $IMAGE_NAME
-
-      - name: "Manejo de errores si el contenedor no se encuentra"
-        run: |
-          if ! docker ps | grep -q $IMAGE_NAME; then
-            echo "Error: El contenedor no se ha creado correctamente."
-            exit 1
-          fi
 
       - name: "Confirmación de finalización"
         run: echo "El flujo de trabajo se ha completado con éxito."
